name: 'Blog Post Workflow'
author: 'Gautam Krishna R'
description: 'Allows you to show your latest blog posts on your github profile or project readme'

inputs:
  gh_token:
    description: 'GitHub access token with Repo scope'
    required: false
    default: ${{ github.token }}
  readme_path:
    description: 'Path of the readme file you want to update'
    default: './README.md'
    required: false
  max_post_count:
    description: 'Maximum number of posts you want to show on your readme, all feeds combined'
    default: '5'
    required: false
  feed_list:
    description: "Comma separated list of RSS feed urls"
    default: ""
    required: true
  disable_sort:
    description: "Disables the sorting of list based on publish date"
    default: "false"
    required: false
  filter_comments:
    description: "Comma separated list of platforms you want to enable the comment filter"
    default: "medium,stackoverflow/Comment by $author/,stackexchange/Comment by $author/"
    required: false
  tag_post_pre_newline:
    description: "Inserts newline before the closing tag and after the opening tag when using the template option, for formatting"
    required: false
  template:
    description: "Template to use while creating the list of posts. It can contain $title,$url, $newline and $date as variables"
    default: "default"
    required: false
  date_format:
    description: "Allows you to change the format of the date or time displayed when using the $date in the template option"
    default: "UTC:ddd mmm dd yyyy h:MM TT"
    required: false
  comment_tag_name:
    description: "Override the default comment tag name, if you want to show multiple instances of the action on the same repo"
    required: false
  user_agent:
    description: "Allows you to customize the user agent used by the RSS feed crawler"
    default: "rss-parser"
    required: false
  accept_header:
    description: "Allows you to customize the accept header of the http request"
    default: "application/rss+xml"
    required: false
  custom_tags:
    description: "Allows you to use the custom tags from your feed items in your template"
    default: ""
    required: false
  title_max_length:
    description: "Allows you to trim the title in the posts list"
    default: ""
    required: false
  description_max_length:
    description: "Allows you to trim the description in the posts list"
    default: ""
    required: false
  item_exec:
    description: "Allows you to execute custom JavaScript code on each item to do advanced text manipulation"
    default: ""
    required: false
  commit_message:
    description: "Commit message used while committing to the repo"
    default: "Updated with the latest blog posts"
    required: false
  committer_username:
    description: "Username used while committing to the repo"
    default: "blog-post-bot"
    required: false
  committer_email:
    description: "Email id used while committing to the repo"
    default: "blog-post-bot@example.com"
    required: false
  output_only:
    description: "Prevent updating the readme, instead sets the output to the output variable named `results`"
    default: "false"
    required: false
  enable_keepalive:
    description: "Enables the feature that keeps the repo active by automatically committing to it even though there is no change"
    default: "true"
    required: false
  retry_count:
    description: "Maximum number of times to retry the fetch operation if it fails"
    default: "0"
    required: false
  retry_wait_time:
    description: "Time to wait before each retry operation in seconds"
    default: "1"
    required: false
outputs:
  results:
    description: "JSON stringified array of posts"

runs:
  using: node12
  main: dist/blog-post-workflow.js
branding:
  icon: 'activity'
  color: 'blue'
