# This is a basic workflow to help you get started with Actions
name: latest blog posts workflow
  
# Controls when the workflow will run
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every day at 12 am
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-readme-with-blog:
    name: Update this repository README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DuncanFaulkner/blog-post-workflow@master
        with:
          feed_list: "https://anglebrackets-dev.medium.com/"
